### ISSUE TITLE
`FilterFindCorrelation` needs adjustment after latest {pillar} update

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#117]
https://github.com/mlr-org/mlr3filters/runs/4977895354?check_suite_focus=true

```
  ── Error (test_FilterFindCorrelation.R:1:1): FilterImportance ──────────────────
  Error: 'type_sum' is not an exported object from 'namespace:pillar'
```

**Comment by mllg** [comment]
This was not a problem of the filter, probably an issue with tidyverse/tic.

**Comment by pat-s** [comment]
Pillar caused it, as stated in the title. Luckily the maintainer is one of my colleagues 😄
