### ISSUE TITLE
FilterPerformance should not have default "classif.featureless" for the learner

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3filters#130]
I guess this is because of the dictionary?

**Comment by sebffischer** [comment]
@pat-s

**Comment by mllg** [comment]
What would be a better default?

**Comment by sebffischer** [comment]
`classif.featureless` gives the same performance for each feature, because the feature is unused. 
I think that is a pretty bad default. 
Also I don't think a default should presuppose a task type.

**Comment by sebffischer** [comment]
If there is no good default then I think we should not set a default

**Comment by pat-s** [comment]
I think the idea is that users do not just rely on the default when using it and at least think about the default once before using it.

Any other "meaningful" default would be complicated to justify and maybe induce the assumption of this being "the best" one to take. 

Not setting a default might also be an option I'd consider, we hand over a learner in tests and examples anyhow. The dictionary should not be an issue AFAICS. @mllg your opinion?

**Comment by mllg** [comment]
We have the convention that every object in the dictionary can be initialized without providing additional arguments. This saves us a lot of trouble for listing the contents of dicts. Sometimes this just does not make sense, and pipelines has some workaround for these cases IIRC.

If we initialized with `NULL` here, we would not have a task type, supported feature types or a param set. This is fine, and we could provide an active binding to set a learner after initialization which also sets these fields to meaningful values, but I'm not sure if this is worth the effort here.

**Comment by pat-s** [comment]
I think for most people having `classif.featureless` as the default should be quite descriptive, i.e. equal to "no default" in practice.

I guess we conclude to leave it as it is?
