### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#22]
In _mlr_ we use the _memoise_ pkg for caching.
I saw that Tasks are cached in _mlr3_ already via this [PR](https://github.com/mlr-org/mlr3/pull/46/files).

@mllg Would this concept also be preferrable for the filters or does it have any limitations? And should we rely on the _memoise_ pkg for caching?

**Comment by mb706** [comment]
btw, `mlr3` attaches a `$hash` to most things, so there may be a way to avoid calculating the digest for input tasks (as `memoise` would probably do it) and speed things up.

**Comment by pat-s** [comment]
_memoise_ caches the whole function call and all of its arguments. Not sure if the hashed task would have any effect here.

**Comment by mb706** [comment]
The return object of `memoise::cache_memory` and `memoise::cache_filesystem` contain the hash function that the these cache mechanisms should use in the `$digest` slot. It would be possible to modify this to consider the `$hash` of input tasks instead of running `digest::digest` on them.

**Comment by pat-s** [comment]
@mb706 AFAIR caching is done in pipelines, isn't it? Hence I would close here if we can find/already have an overarching solution.

**Comment by mb706** [comment]
Caching is on the way to be implemented in pipelines ([here](https://github.com/mlr-org/mlr3pipelines/pull/382)), but not there yet. But I agree that it is probably redundant to have filtering here once it is also in pipelines.

**Comment by pat-s** [comment]
Cool, thanks. Then I won't put more thoughts about this in here 🙂
