### ISSUE TITLE
Implementation of "wrapper" methods

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#24]
Sticking closely to the implementation in _mlr3tuning_.

## Methods

Ported from what we have in _mlr_.

- [ ]  Exhaustive search makeFeatSelControlExhaustive

- [ ] Genetic algorithm makeFeatSelControlGA

- [ ] Random search makeFeatSelControlRandom

- [ ] Deterministic forward or backward search makeFeatSelControlSequential

cross-ref #2

**Comment by pat-s** [comment]
_mlr3tuning_ uses the `AutoTuner` class as a wrapper for automated tuning in nested resampling.
We should also implement the wrapper methods in a class `AutoSelect` (or a similar name) to stay consistent.

**Comment by mllg** [comment]
AFAICT all methods are implemented (not reviewed though) in mlr3fswrap. Closing here.
