### ISSUE TITLE
Think about how to implement PCA

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#31]
In _mlr_ we used `makePreprocWrapperCaret()`.

**Comment by mllg** [comment]
There was a filter for PCA in mlr?

**Comment by pat-s** [comment]
The only reference I could find was via `makePreprocWrapperCaret()`.

We may want to use a package for that instead of doing the work on our own.

**Comment by mllg** [comment]
I don't get what this filter is supposed to do. Do you want to extract features based on their loadings on the PCs?

You can do PCA with `prcomp()` or `princomp()` from `stats`.

**Comment by jakob-r** [comment]
Just to rule out the obvious: We are not talking about the normal [PCA that is a PipeOp](https://mlr3pipelines.mlr-org.com/reference/mlr_pipeop_pca.html) right?

**Comment by berndbischl** [comment]
I also don't get what a pca filter should do. If no one can link to a rather standard paper that discusses this, the issue should be closed imho

**Comment by mllg** [comment]
Well, the score could be the explained variance. That would not be too extraordinary.

**Comment by pat-s** [comment]
I guess my initial thinking when opening this issue was that all operations that perform "feature selection" in any way should be placed in here - when the package was still called "mlr3featsel" and we wanted to include wrappers, filters and PCA (on the same level).

Now lots has changed and we only have filters in here and yes, PCA is already supported via a PipeOp. 

I did not have in mind implementing PCA as a filter (I also do not see how that should make sense) but as a standalone "feature selection" method.

**Comment by berndbischl** [comment]
Michel said. Well, the score could be the explained variance. That would not be too extraordinary.

Well that does make sense. If someone wants this, this could be implemented
