### ISSUE TITLE
Feature importance calculation

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3filters#33]
The name for the function to calculate a ranking for feature importance is `calculate()` -- this is very non-descriptive and non-intuitive. I propose to rename to `ranking()`.

**Comment by larskotthoff** [comment]
I like the idea of making it internal and calling it automatically, but then the name of the function to get the values should arguably be `get()`.

Is there any scenario where it makes sense to get the values not in rank order? If not, I don't see why there should be a separate function to do that.

**Comment by pat-s** [comment]
> I like the idea of making it internal and calling it automatically, but then the name of the function to get the values should arguably be get().

Values are simply stored in `filter$scores`, so there is no getter needed.

> Is there any scenario where it makes sense to get the values not in rank order? If not, I don't see why there should be a separate function to do that.

I do not know of any right now. Michel coded it like that explicitly for some reason, maybe because this is also the behavior of mlr? `generateFilterValuesData()` returns the values shuffled, only `filterFeatures()` is doing the ranking.

**Comment by pat-s** [comment]
@larskotthoff 	see https://github.com/mlr-org/mlr3featsel/issues/28#issuecomment-503750193

**Comment by pat-s** [comment]
The functionality has been trimmed down to the following:

-  `Filter$calculate(task)` calculates the filter values and stores them in `$scores`

- The resulting data.table can be extracted via `as.data.table()` and then post-processed as usual, e.g. `head(as.data.table(filter), 3)`

- all Task operations (e.g. subsetting) should be done with mlr3pipelines or manually using the operators of class `Task`.
