### ISSUE TITLE
Filter request: ReliefF

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#38]
"This filter is an extension of the original Relief
algorithm [31] that works by randomly sampling an instance
from the dataset and then locating its nearest neighbor from
the same and opposite class. The values of the nearest neigh-
bor attributes are compared to the sampled instance and used
to update relevance scores for each attribute. The rationale is that a useful attribute should differentiate between instances
from different classes, and have the same value for instances
from the same class. Compared to Relief, ReliefF is more robust,
better handles multiclass problems and incomplete and noisy
data, can be applied in all situations, has low bias, allows in-
teraction among features, and may capture local dependencies
which other methods miss."

Seijo-Pardo, B., Porto-Díaz, I., Bolón-Canedo, V., & Alonso-Betanzos, A. (2017). Ensemble feature selection: Homogeneous and heterogeneous approaches. Knowledge-Based Systems, 118, 124–139. https://doi.org/10/f9qgrv

-> This is available in `FSelector::relief()` but we would like to avoid _FSelector_ due to its Java dep.

**Comment by mllg** [comment]
Maybe we can request this filter to be included into FSelectorRcpp?

**Comment by pat-s** [comment]
FSelectorRcpp now has the Relief filter, waiting for the CRAN release.
