### ISSUE TITLE
Release mlr3filters 0.1.0

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3filters#57]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] Update `cran-comments.md` 
* [ ] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] Update install instructions in README 
* [ ] Finish blog post 
* [x] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by mllg** [comment]
@pat-s there are still some open points on your todo ;)

**Comment by pat-s** [comment]
I'll do it tmrw :)
