### ISSUE TITLE
Filters to remove correlated features and linear combinations

### ISSUE THREAD

**Issue by missuse** [mlr-org/mlr3filters#61]
Hi,

I noticed all of the filters in mlr3 look at the relationship between the features and the outcome. I
was curious if there are plans to implement filters that look at the relationship between the features,  similar to the caret functions:

[findCorrelation](https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/findCorrelation)

[findLinearCombos](https://www.rdocumentation.org/packages/caret/versions/6.0-85/topics/findLinearCombos)

Thanks

**Comment by mllg** [comment]
I'm unsure if this fits in the filters package. The interfaced `subselect` package does not return scores, but instead a set of variables determined iteratively. So this would probably better fit into https://github.com/mlr-org/mlr3fselect?

**Comment by mllg** [comment]
On a second thought, `mlr3fselect` does not fit so well either.

**Comment by berndbischl** [comment]
i do think this fits

**Comment by pat-s** [comment]
These funs look like preprocessing funs and should (if) then go into {mlr3pipelines}.

Thanks for mentioning though!

**Comment by missuse** [comment]
The `findCorrelation` function returns a subset of the input features. The number of features in the subset is based on a certain tunable threshold . This seems to fit with mlr3filters, at least to me. 

`findLinearCombos` functions just removes some features and is not tuneable.  It does look to be better suited for `mlr3pipelines`, maybe even implemented as selector function to be used with `PipeOpSelect`.

**Comment by pat-s** [comment]
> The findCorrelation function returns a subset of the input features. The number of features in the subset is based on a certain tunable threshold . This seems to fit with mlr3filters, at least to me.

Does it also return the scores?

How does it differ to the existing correlation filters?

**Comment by missuse** [comment]
>Does it also return the scores?

No it does not. And it is not obvious to me how would the scores be calculated. They return a subset of the features that should be removed based on the specified threshold.

> How does it differ to the existing correlation filters?

The existing correlation filters check the correlation between the target and each feature and rank features based on the absolute correlation. Basically they favor keeping mutually highly correlated features which are also highly correlated to the target.

On the other hand  `findCorrelation` checks the pairwise correlation between the features and removes features so that no two features have higher absolute correlation then the specified threshold.  Highly correlated features cause instability in some learners and they contain overlapping information so keeping them is unlikely to benefit learners that can sustain them.

**Comment by pat-s** [comment]
> No it does not. And it is not obvious to me how would the scores be calculated. It returns a subset of the features that should be removed based on the specified threshold.

This is the problem: We do not subset in {mlr3filters} and only return a (ranked) DT of the filter values + features. Doing the ranking & subsetting directly is a full preprocessing method that should go into {mlr3pipelines} or {mlr3fselect}.

The ranking going on behind the scenes within `findCorrelation()` would be a candidate for a new filter. This would then be the calculation of

>  the pairwise correlation between the features

---

> Highly correlated features cause instability in some learners and they contain overlapping information so keeping them is unlikely to benefit learners that can sustain them.

This is a decision step what to do with the results after the ranking has been computed.
To make sense as a filter you could invert this ranking, i.e. the ones with the lowest score (i.e. the lower pairwise correlation) are the "best" features and will more likely to be kept.

So if you want to dig in, feel free to open a PR :) Or more generally, propose a "pairwise correlation filter" to be added.

**Comment by missuse** [comment]
Yeah, I understand now.

The problem with `findCorrelation()` is that no ranking is going on behind the scenes. It basically checks which pairs of features have `abs(cor())` above the specified threshold and removes one feature for which this happens most frequently (feature with most pairwise correlations above the threshold). This is iterated until no features are left with a abs(cor()) above the threshold. 

I need to think about it some more. 

Thanks

**Comment by berndbischl** [comment]
I posted bullshit before when I said the methods might make sense here. the problem is:
filters need to generate a score that encodes how "useful" the features are in order to solve the task.

neither method above does that. they calculate something of a secondary nature - "how redundant is a set".
of course this can be used as a COMPONENT in a complex filter calculation. but its not a filter directly on its own.
see the method MRMR which does this. MRMR is of course in scope for mlr3filters
https://en.wikipedia.org/wiki/Minimum_redundancy_feature_selection

**Comment by missuse** [comment]
I implemented it as `PipeOpTaskPreproc`

```
PipeOPfindCor <- R6Class("PipeOPfindCor",
                         inherit = mlr3pipelines::PipeOpTaskPreproc,
                         public = list(
                           initialize = function(id = "findCor", param_vals = list()) {
                             ps = paradox::ParamSet$new(params = list(
                               paradox::ParamLgl$new("exact", tags = c("train", "findCor")),
                               paradox::ParamDbl$new("cutoff", lower = 0, upper = 1, tags = c("train", "findCor"))
                             ))
                             super$initialize(id, param_set = ps, param_vals = param_vals,
                                              packages = "caret")
                           },
                           
                           select_cols = function(task) {
                             task$feature_types[get("type") %in% c("numeric", "integer"), get("id")]
                           },
                           
                           train_dt = function(dt, levels, target) {
                             cols = invoke(caret::findCorrelation, cor(dt), .args = self$param_set$get_values(tags = "findCor"))
                             self$state = list(dt_columns = cols)
                             dt[, -cols, with = FALSE]
                           },
                           
                           predict_dt = function(dt, levels) {
                             dt[, -self$state$dt_columns, with = FALSE]
                           }
                         )
)


mlr_pipeops$add("findCor", PipeOPfindCor)

task = tsk("iris")
pop = po("findCor", param_vals = list(cutoff = 0.9))


pop$train(list(task))[[1]]$data()
       Species Petal.Width Sepal.Length Sepal.Width
  1:    setosa         0.2          5.1         3.5
  2:    setosa         0.2          4.9         3.0
  3:    setosa         0.2          4.7         3.2
  4:    setosa         0.2          4.6         3.1
  5:    setosa         0.2          5.0         3.6
 ---                                               
146: virginica         2.3          6.7         3.0
147: virginica         1.9          6.3         2.5
148: virginica         2.0          6.5         3.0
149: virginica         2.3          6.2         3.4
150: virginica         1.8          5.9         3.0
```

**Comment by pfistfl** [comment]
Hey, @missuse 
Wanna submit this as a PR to `mlr3pipelines`?
Would be nice to have I guess.

**Comment by missuse** [comment]
> Wanna submit this as a PR to `mlr3pipelines`?

Would be my pleasure. Tomorrow I will write a help file and submit it. 

`findCor` - is it an ok name? Maybe better is `rmCor`? Since the function not only finds but also removes correlated features.

**Comment by pfistfl** [comment]
`pipeOpdropCor`? `pipeOprmCor`? `pipeOpdeleteCorelated`? I'll leave it up to you. 
This currently introduces `suggests: caret` which might be alright, but we should keep this in mind.

**Comment by missuse** [comment]
> `pipeOpdropCor`? `pipeOprmCor`? `pipeOpdeleteCorelated`? I'll leave it up to you.
> This currently introduces `suggests: caret` which might be alright, but we should keep this in mind.

I will try to make a function similar to `caret::findCorrelation()`. If it holds fairly well in tests it can be used.

**Comment by pat-s** [comment]
Do you mind switching over to a new issue in pipelines?

Maybe this functionality also already exists in the new tidymodels framework?

PS: I am not sure if Martin would like having {caret} being pulled in as a dep.

**Comment by missuse** [comment]
> Do you mind switching over to a new issue in pipelines?

I apologize for dragging this here.

> Maybe this functionality also already exists in the new tidymodels framework?

It does: [`step_cor()`](https://tidymodels.github.io/recipes/reference/step_corr.html)

> PS: I am not sure if Martin would like having {caret} being pulled in as a dep.

Understandable. I will refrain from opening a PR in pipelines. You guys can add at later if you decide to do so.

**Comment by mb706** [comment]
I believe what [pat-s said earlier](https://github.com/mlr-org/mlr3filters/issues/61#issuecomment-582532396) is the correct way to proceed: Use the cutoff points as score for the filter.

**Comment by mb706** [comment]
Easy way to implement this: copy the caret function, and for each feature store the cutoff point at which the feature would have been removed. idk if there are some license issues?

**Comment by missuse** [comment]
> Easy way to implement this: copy the caret function, and for each feature store the cutoff point at which the feature would have been removed. idk if there are some license issues?

The problem I face in order to implement it this way can be described with the following example:

```
library(caret)
library(mlbench)
data(Sonar)

c88 <- findCorrelation(cor(Sonar[,1:60]), cutoff = 0.88)
c88
[1] 15 16 18 20 48 36

c87 <- findCorrelation(cor(Sonar[,1:60]), cutoff = 0.87)
c87
[1] 15 16 19 18 20 48 35 37 10

all(c88 %in% c87)
[1] FALSE
```
cutoff = 0.88 removes feature 36 but cutoff 0.87 does not

A similar problem can be faced if one tries to implement [`subselect::aneal()`](https://www.rdocumentation.org/packages/subselect/versions/0.14/topics/anneal) as a  filter.

The first example 
```
data(swiss)
anneal(cor(swiss),2,3,nsol=4,niter=10,criterion="RM")
``` 
shows that the best 2 feature subset contains features 3 and 6, while the best three feature subset contains features 4, 5 and 6

**Comment by mb706** [comment]
At least the `exact = FALSE` version could be implemented, it seems to be monotonic:

(y axis: cutoff, x axis: feature position. yellow: feature is excluded, red: feature stays)
![fast](https://user-images.githubusercontent.com/15801081/74224301-e2bdbb80-4cb8-11ea-8536-d2824548c5e7.png)

`exact = TRUE` is not so nice:
![slow](https://user-images.githubusercontent.com/15801081/74224444-26b0c080-4cb9-11ea-9bde-4c98d141931e.png)
