### ISSUE TITLE
glmnet (LASSO) learners capable of determining variable importance

### ISSUE THREAD

**Issue by shudras** [mlr-org/mlr3filters#74]
LASSO implemented in glmnet and available in mlr3 (e.g. regr.glmnet) is a learner capable of extracting variable importance from the fitted model, but not yet in the mlr3learners package.

**Comment by pat-s** [comment]
Thanks.

We are tracking this in {mlr3learners} already: https://github.com/mlr-org/mlr3learners/issues/28

**Comment by mllg** [comment]
There is no importance for glmnet learners, but you can extracted the features with non-zero coefficients with `$selected_features()`. For filtering, use `FilterSelectedFeatures()` (`flt("selected_features")`).

**Comment by albersonmiranda** [comment]
@mllg , would you mind providing reprex of selected_features method? I'm having a real hard time

**Comment by mllg** [comment]
The code is implemented in the learners, e.g. https://github.com/mlr-org/mlr3learners/blob/main/R/LearnerRegrGlmnet.R#L97 which calls functions from https://github.com/mlr-org/mlr3learners/blob/main/R/helpers_glmnet.R.

There are a lot of if-else blocks to cover all ways to call the learner which all yield slightly different objects. One way to extract the selected features is to predict the non-zero betas:

```r
  nonzero = predict(self$model, type = "nonzero", s = lambda)
 ```

Hope this helps.
